name: Rust

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    install_linker:
        name: Install packages
        runs-on: ubuntu-latest
        steps:
            - name: Install linker
              run: sudo apt update && sudo apt install build-essential qemu-system-x86
    build:
        needs: [install_linker]
        name: Compile and test the executable
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install latest nightly
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt, clippy

            # `cargo check` command here will use installed `nightly`
            # as it is set as an "override" for current directory

            - name: add additional components
              run: rustup component add llvm-tools-preview rust-src

            - uses: actions/checkout@v2
            - name: Run tests
              run: cargo test

            - uses: actions/checkout@v2
            - name: Build
              run: cargo build
